In [ ]:
for condition {
statement1
    statement 2
}
statement3

In [ ]:
for condition:
    statement1
    statement2
statement3


In [1]:
stunames = ['Harshal','Priyanka','Khushal','Milind']

In [5]:
list(range(0,6))

[0, 1, 2, 3, 4, 5]

In [10]:
for i in range(0,6):
    print(i)
    print('Hi')
print('Hello')

0
Hi
1
Hi
2
Hi
3
Hi
4
Hi
5
Hi
Hello


In [18]:
stunames = ['Harshal','Priyanka','Khushal','Milind']
rollno = (1,2,3,4)

In [13]:
for nagpur in stunames:
    print('Hi',nagpur)

Hi Harshal
Hi Priyanka
Hi Khushal
Hi Milind


In [19]:
for (s,r) in zip(stunames,rollno):
    print('Hello', s, ',', 'Your roll no is:', r)

Hello Harshal , Your roll no is: 1
Hello Priyanka , Your roll no is: 2
Hello Khushal , Your roll no is: 3
Hello Milind , Your roll no is: 4


In [20]:
sales = [2343,5443,2334,4433]
profit = [435,334,234,333]

In [21]:
profit/sales

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [23]:
list(range(0,4))

[0, 1, 2, 3]

In [31]:
profitratio = []
for i in range(0,len(sales)):
    profitratio.append(profit[i]/sales[i])
profitratio

[0.1856594110115237,
 0.06136321881315451,
 0.10025706940874037,
 0.07511842995713963]

In [24]:
import numpy as np

In [26]:
sales_array=np.array(sales)

In [28]:
profit_array=np.array(profit)

In [29]:
profit_array/sales_array

array([0.18565941, 0.06136322, 0.10025707, 0.07511843])

In [52]:
list1 = [10, False]

In [36]:
type(list1[3])

bool

In [53]:
array1=np.array(list1)

In [54]:
array1

array([10,  0])

In [59]:
sales*3

[2343, 5443, 2334, 4433, 2343, 5443, 2334, 4433, 2343, 5443, 2334, 4433]

In [57]:
sales_array*2

array([ 4686, 10886,  4668,  8866])

In [61]:
sales_array1 = sales_array[1:3]

In [67]:
sales_array[2]=1000

In [70]:
sales_array2=sales_array.copy()

In [75]:
sales_array

array([2343, 2222, 1000, 4433])

In [73]:
sales_array2[0]=2000

In [74]:
sales_array2

array([2000, 2222, 1000, 4433])

In [64]:
sales_array1[0]=2222

In [69]:
sales_array1

array([2222, 1000])

In [76]:
type(sales_array)

numpy.ndarray

In [77]:
sales_us = [2323,4334,3344,3233]
sales_eu = [5545,6667,4455,3444]
sales_jp = [5444,3443,4445,6555]

In [81]:
sales_matrix = np.array((sales_us, sales_eu, sales_jp))

In [89]:
sales_matrix[1,2]

4455

In [86]:
profit_matrix = np.array([[435,566,555,444], [676,434,565,333], [654,777,566,454]])

In [88]:
profit_matrix/sales_matrix

array([[0.18725786, 0.13059529, 0.1659689 , 0.13733375],
       [0.12191163, 0.06509675, 0.12682379, 0.0966899 ],
       [0.12013226, 0.22567528, 0.12733408, 0.06926011]])

In [96]:
sales_matrix

array([[2323, 4334, 3344, 3233],
       [5545, 6667, 4455, 3444],
       [5444, 3443, 4445, 6555]])

In [91]:
rdict={'US':0, 'EU':1, 'JP':2}

In [92]:
qdict={'Q1':0,'Q2':1,'Q3':2,'Q4':3}

In [94]:
sales_matrix[rdict['EU']][qdict['Q4']]

3444

In [97]:
sales_array=np.array([2343,4434,3333,5434,5433,2323,4433,5444,3333,4344,2233,2233])

In [98]:
sales_array

array([2343, 4434, 3333, 5434, 5433, 2323, 4433, 5444, 3333, 4344, 2233,
       2233])

In [100]:
np.reshape(sales_array,(3,4), 'C')

array([[2343, 4434, 3333, 5434],
       [5433, 2323, 4433, 5444],
       [3333, 4344, 2233, 2233]])

In [101]:
np.reshape(sales_array,(3,4), 'F')

array([[2343, 5434, 4433, 4344],
       [4434, 5433, 5444, 2233],
       [3333, 2323, 3333, 2233]])

In [102]:
np.sqrt(100)

10.0

In [106]:
list1= [1,2,3,4,5]

In [107]:
list1.insert(5,100)

In [110]:
list1*3

[1, 2, 3, 4, 5, 100, 1, 2, 3, 4, 5, 100, 1, 2, 3, 4, 5, 100]